/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesCloudInfrastructureRouteImport } from './routes/services/cloud-infrastructure'
import { Route as ServicesDataAiRouteImport } from './routes/services/data-ai'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services/digital-marketing'
import { Route as ServicesItConsultingStaffingRouteImport } from './routes/services/it-consulting-staffing'
import { Route as ServicesSecurityRouteImport } from './routes/services/security'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services/software-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudInfrastructureRoute =
  ServicesCloudInfrastructureRouteImport.update({
    id: '/services/cloud-infrastructure',
    path: '/services/cloud-infrastructure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDataAiRoute = ServicesDataAiRouteImport.update({
  id: '/services/data-ai',
  path: '/services/data-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/services/digital-marketing',
    path: '/services/digital-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesItConsultingStaffingRoute =
  ServicesItConsultingStaffingRouteImport.update({
    id: '/services/it-consulting-staffing',
    path: '/services/it-consulting-staffing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSecurityRoute = ServicesSecurityRouteImport.update({
  id: '/services/security',
  path: '/services/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/services/software-development',
    path: '/services/software-development',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/cloud-infrastructure': typeof ServicesCloudInfrastructureRoute
  '/services/data-ai': typeof ServicesDataAiRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/it-consulting-staffing': typeof ServicesItConsultingStaffingRoute
  '/services/security': typeof ServicesSecurityRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/cloud-infrastructure': typeof ServicesCloudInfrastructureRoute
  '/services/data-ai': typeof ServicesDataAiRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/it-consulting-staffing': typeof ServicesItConsultingStaffingRoute
  '/services/security': typeof ServicesSecurityRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/cloud-infrastructure': typeof ServicesCloudInfrastructureRoute
  '/services/data-ai': typeof ServicesDataAiRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/it-consulting-staffing': typeof ServicesItConsultingStaffingRoute
  '/services/security': typeof ServicesSecurityRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/services/cloud-infrastructure'
    | '/services/data-ai'
    | '/services/digital-marketing'
    | '/services/it-consulting-staffing'
    | '/services/security'
    | '/services/software-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/services/cloud-infrastructure'
    | '/services/data-ai'
    | '/services/digital-marketing'
    | '/services/it-consulting-staffing'
    | '/services/security'
    | '/services/software-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/services/cloud-infrastructure'
    | '/services/data-ai'
    | '/services/digital-marketing'
    | '/services/it-consulting-staffing'
    | '/services/security'
    | '/services/software-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ServicesCloudInfrastructureRoute: typeof ServicesCloudInfrastructureRoute
  ServicesDataAiRoute: typeof ServicesDataAiRoute
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesItConsultingStaffingRoute: typeof ServicesItConsultingStaffingRoute
  ServicesSecurityRoute: typeof ServicesSecurityRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-infrastructure': {
      id: '/services/cloud-infrastructure'
      path: '/services/cloud-infrastructure'
      fullPath: '/services/cloud-infrastructure'
      preLoaderRoute: typeof ServicesCloudInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-ai': {
      id: '/services/data-ai'
      path: '/services/data-ai'
      fullPath: '/services/data-ai'
      preLoaderRoute: typeof ServicesDataAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/services/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/it-consulting-staffing': {
      id: '/services/it-consulting-staffing'
      path: '/services/it-consulting-staffing'
      fullPath: '/services/it-consulting-staffing'
      preLoaderRoute: typeof ServicesItConsultingStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/security': {
      id: '/services/security'
      path: '/services/security'
      fullPath: '/services/security'
      preLoaderRoute: typeof ServicesSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/services/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ServicesCloudInfrastructureRoute: ServicesCloudInfrastructureRoute,
  ServicesDataAiRoute: ServicesDataAiRoute,
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesItConsultingStaffingRoute: ServicesItConsultingStaffingRoute,
  ServicesSecurityRoute: ServicesSecurityRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
